### ISSUE TITLE
EURALCODE in OTM

### ISSUE THREAD

**Issue by wzentjens** [opentripmodel/opentripmodel#50]
At the moment the EURALCODE is not yet available in the latest version of OTM. It could be a good and logical addition. 

Info:

https://sutc.semantictreehouse.nl/api/v1/uploads/FileObject_1527195075_00087938/140204%20EBA%20standaard%201.1%20definitief.pdf

**Comment by bmeesters** [comment]
Hello @wzentjens, note that this repository is used for OTM4 and is not actively maintained anymore. If you want to make a change to OTM5, you should create an issue here: https://github.com/opentripmodel/otm5-change-requests

**Comment by wzentjens** [comment]
Thanks & done.
